### ISSUE TITLE
Optionally auto-connect to the current VPN server location

### ISSUE THREAD

**Issue by hensm** [hensm/mullvad-proxy#3]

**Comment by NewRedsquare** [comment]
+1 for this, could be very useful

**Comment by hensm** [comment]
Looking to work on this again soon, just juggling a lot of projects at the moment.

I suppose if they were interested in a browser extension, they probably would have made one by now. It's much less work than the desktop client.

**Comment by hensm** [comment]
WIP: #5 
![options_ui](https://user-images.githubusercontent.com/6956633/107835961-49c1f480-6d93-11eb-852b-25916d2c21d1.png)
