### ISSUE TITLE
Option to exclude domains [feature request]

### ISSUE THREAD

**Issue by neekt** [hensm/mullvad-proxy#7]
Firstly, great extension! I just discovered it and it works perfectly.

Just a thought; one useful feature that could be added to this would be a whitelist (or blacklist?) option for excluding specified domains from being proxied. If it's possible and if you have the time/motivation for it :)

Thanks for maintaining this.

**Comment by hensm** [comment]
Thanks, glad you find it useful!

This was actually the next thing I was going to work on, so it'll probably be in the next release, whenever I have time to implement it.

**Comment by hensm** [comment]
9c405f1

**Comment by worldpe** [comment]
How do you use this feature? I want to be able to see locally hosted webpages, but I can't get it to work. In my case I want to exclude ```10.64.13.192:4567```, I have all these things in the list, but none of them are working 
![image](https://github.com/hensm/mullvad-proxy/assets/82988612/24e5748b-6f06-4dd4-a468-1bd15232d9d5)
